### ISSUE TITLE
Remove the use of apikeys/accesstokens for application level authorization between song and score

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#595] opened 2020-02-19 17:44 UTC
## Background
Currently, `song-server` requires an apikey with score.WRITE inorder to download the object specification from `score-server` which contains MD5 and size information in order to validate analyses before publishing them.

If a user DOES NOT have score.WRITE, but has song.WRITE, they should still be able to publish the analysis, which is why song needs an application level apiKey or form of authorization.

ApiKeys are meant for user-to-machine authorization and have a short expiry , and not for machine-to-machine authorization which may not have an expiry.

### 1. Apikey ownership 
Since a users own an apiKeys, this means a user would have to make an apiKey and configure `song-server` to use it. Even in a non-prod environment, an application operation should not depend on a single user. 
 
### 2. Apikey expiry 
Even if 1) is ignored, given that apiKeys have a short expiry, maintaining them by a single user is another point of failure and causes unnecessary overhead. In a prod environment, this can risk downtime and bad user experiences when the apiKeys expire. 

### 1. ClientID and ClientSecret Credentials
Assuming traffic between `song-server` and `score-server` is encrypted, song should be able to make requests to score using song's clientId and clientSecret. Score would use the client secrets to validate they have permission. Since this is machine-to-machine communication, this is acceptable.

### 2. Legit Application Level ApiKeys/JWTs   
This would be more of a modification in EGO, however assuming applications can own apikeys or tokens, one can be created for song with the score.WRITE scope to access score. Score would then be able to validate the apikey the same way as before. This would require alot more work on ego side.

**Comment by rosibaj** [comment] 2020-02-20 04:04
@rtisma we've had several discussions with @andricDu in the past about Application level keys/JWTs, which we have never pursued.  Why would this not be a time to use clientid/client id credentials?

**Comment by andricDu** [comment] 2020-03-30 18:14
This might be a falls dichotomy. ClientIDs and ClientSecrets are used to obtain Application JWTs. This is part of the client credentials flow as described by the OAuth2.0 spec. 

Client secrets are not used to authorize. They are used to Authenticate. The application JWT returned from the OAuth2.0 flow to the application is then the object used for authorization. 

The real question being asked is, do we want to associated applications to policies, and then have that reflected in the application JWT.

**Comment by rosibaj** [comment] 2020-06-23 20:15
@rtisma @andricDu i think this is covered by: https://github.com/overture-stack/ego/issues/467 

is that right?

**Comment by rosibaj** [comment] 2020-11-24 20:26
reconfirming the duplicate note today - i believe this has been taken care of.

**Comment by rosibaj** [comment] 2020-11-24 20:33
Duplicate of https://github.com/overture-stack/roadmap/issues/90

**Closed** 2020-11-24 20:33 UTC
Labels: critical, duplicate, grooming, new-feature, specs-wip
